version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_llm_function_calling
    gpus:
      - all
    ports:
      - 11434:11434
    volumes:
      - ./ollama_data:/root/.ollama
  python:
    image: python
    container_name: python_llm_function_calling
    volumes:
      - ./app:/app
    working_dir: /app
    command:
      - sh
      - -c
      - pip install --upgrade pip && pip install -r requirements.txt && python ${APP:-weather}.py
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    depends_on:
      - ollama
